/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const superheroes_Logic = require('./code/superheroes-logic');

class full_stack_appSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'SuperHeroes', async (request, next) => {
            await superheroes_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    full_stack_appSrv
};